//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public int id_car { get; set; }
        public int id_parlot { get; set; }
    
        public virtual Parking_Lot Parking_Lot { get; set; }
        public virtual Car Car { get; set; }
    }
}
