//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking_Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking_Lot()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int id { get; set; }
        public int id_car { get; set; }
        public int id_employee { get; set; }
        public string title_car { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Car Car { get; set; }
    }
}
