//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int id { get; set; }
        public int id_car { get; set; }
        public int id_employee { get; set; }
        public string road { get; set; }
        public string way { get; set; }
        public int id_client { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Car Car { get; set; }
    }
}
